apiVersion: v2
name: wiz-kubernetes-integration
description: A Helm chart for Kubernetes
type: application
version: 0.2.88
appVersion: ""

# Dependencies for wiz-kubernetes connector and wiz-admission-controller and wiz-sensor
dependencies:
- name: wiz-kubernetes-connector
  repository: "file://../wiz-kubernetes-connector"
  version: ">=3.1.0"
  condition: wiz-kubernetes-connector.enabled
- name: "wiz-admission-controller"
  repository: "file://../wiz-admission-controller"
  version:  ">=3.6.0"
  condition: wiz-admission-controller.enabled
- name: wiz-sensor
  repository: "file://../wiz-sensor"
  version: ">=1.0.6187"
  condition: wiz-sensor.enabled
- name: wiz-common
  version: "0.1.8"
  repository: "file://../wiz-common"
- name: wiz-broker
  repository: "file://../wiz-broker"
  version: "2.3.9"
  condition: wiz-kubernetes-connector.broker.enabled